
services:

  server:
    build: .
    image: bacnet
    command: ["bacserv", "200001"]
    ports:
      - "14780:47808/udp"
    environment:
      - BACNET_IP_PORT=47808
      - BACNET_IP_BROADCAST=255.255.255.255
    restart: unless-stopped

  # Pump values into server.
  # TODO: Needs more convenient Env based config
  simulator:
    image: bacnet
    depends_on:
      - server
    command: ["perl", "/simulator"]
    restart: unless-stopped
    
